// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/remembrance-brain/Current.tsx": () => import("../components/mockups/remembrance-brain/Current.tsx"),
  "./components/mockups/remembrance-brain/PentagonConcept.tsx": () => import("../components/mockups/remembrance-brain/PentagonConcept.tsx")
};
