// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/assessment-directions/Clarity.tsx": () => import("../components/mockups/assessment-directions/Clarity.tsx"),
  "./components/mockups/assessment-directions/Companion.tsx": () => import("../components/mockups/assessment-directions/Companion.tsx"),
  "./components/mockups/assessment-directions/Sanctuary.tsx": () => import("../components/mockups/assessment-directions/Sanctuary.tsx"),
  "./components/mockups/home-directions/DashboardSoft.tsx": () => import("../components/mockups/home-directions/DashboardSoft.tsx"),
  "./components/mockups/home-directions/OuraCalm.tsx": () => import("../components/mockups/home-directions/OuraCalm.tsx"),
  "./components/mockups/home-directions/WatchRings.tsx": () => import("../components/mockups/home-directions/WatchRings.tsx"),
  "./components/mockups/remembrance-brain/Current.tsx": () => import("../components/mockups/remembrance-brain/Current.tsx"),
  "./components/mockups/remembrance-brain/PentagonConcept.tsx": () => import("../components/mockups/remembrance-brain/PentagonConcept.tsx")
};
